### ISSUE TITLE
KAAE Tutorial

### ISSUE THREAD

**Issue by cherweg** [sirensolutions/kaae#63]
Hi.
I cant get the example working. 

My environment:
   Elasticsearch: 2.4.1 (loadbalanced over an http Proxy on Port 80)
   Kibana: 4.6.3 (Centos7-Docker-Container)

I followed stepbystep the example. (except setting schedule to 30 seconds)

The debug log of my kibana only says:
`
{"type":"log","@timestamp":"2016-11-18T11:36:29Z","tags":["status","info","KaaE"],"pid":1,"message":"KaaE Initializing"}
{"type":"log","@timestamp":"2016-11-18T11:36:29Z","tags":["status","info","KaaE"],"pid":1,"message":"Core Index check..."}
{"type":"log","@timestamp":"2016-11-18T11:36:29Z","tags":["status","info","KaaE"],"pid":1,"message":"Alarm Index check..."}
{"type":"log","@timestamp":"2016-11-18T11:36:29Z","tags":["status","debug","KaaE"],"pid":1,"message":"Reloading Watchers..."}
{"type":"log","@timestamp":"2016-11-18T11:36:29Z","tags":["status","debug","KaaE"],"pid":1,"message":"Core Index exists!"}
{"type":"log","@timestamp":"2016-11-18T11:36:29Z","tags":["status","debug","KaaE"],"pid":1,"message":"Alarms Index exists!"}
{"type":"log","@timestamp":"2016-11-18T11:36:29Z","tags":["status","info","KaaE"],"pid":1,"message":"Scheduled Watch: mos every every 30 seconds"}
{"type":"log","@timestamp":"2016-11-18T11:36:30Z","tags":["status","info","KaaE"],"pid":1,"message":"Executing watch: mos"}
{"type":"log","@timestamp":"2016-11-18T11:36:30Z","tags":["status","debug","KaaE","WATCHER DEBUG"],"pid":1,"message":"{ _index: 'watcher',\n  _type: 'watch',\n  _id: 'mos',\n  _score: 1,\n  _source: \n   { trigger: { schedule: [Object] },\n     input: { search: [Object] },\n     condition: { script: [Object] },\n     transform: { search: [Object] },\n     actions: { console: [Object] } } }"}
`

If i manually query the mos-index this is the response:

{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 88,
    "max_score": 1,
    "hits": [
      {
        "_index": "mos-2016.11.18",
        "_type": "mos",
        "_id": "AVh3NH2wrJ1XY3jJO-Mi",
        "_score": 1,
        "_source": {
          "mos": 5,
          "@timestamp": "2016-11-18T11:31:18.561"
        }
      },
      {
        "_index": "mos-2016.11.18",
        "_type": "mos",
        "_id": "AVh3NIl-rJ1XY3jJO-Mj",
        "_score": 1,
        "_source": {
          "mos": 4,
          "@timestamp": "2016-11-18T11:31:21.584"
        }
      },
    [.... here where some other Results]
    ]
  },
  "aggregations": {
    "avg": {
      "value": 2.8863636363636362
    }
  }
}

I was wondering why no alarm was created and no more debug messages logged.

Any idea?

regards
Christian

**Comment by lmangani** [comment]
Hi @cherweg it appears the condition is not being matched for execution. 
To confirm if this is the case, you can try change the following and set Kibana logs to verbose:
```
"condition": {
      "script": {
        "script": "payload.hits.total > 1"
      }
    },
    "transform": {},
```

**Comment by cherweg** [comment]
Yes I followed the wiki tutorial.
I modified the watch as requested without any success:
```json
{
  "_index": "watcher",
  "_type": "watch",
  "_id": "mos",
  "_score": 1,
  "_source": {
    "trigger": {
      "schedule": {
        "later": "every 55 seconds"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": [
            "<mos-{now/d}>",
            "<mos-{now/d-1d}>"
          ],
          "body": {
            "query": {
              "filtered": {
                "query": {
                  "query_string": {
                    "query": "mos:*",
                    "analyze_wildcard": true
                  }
                },
                "filter": {
                  "range": {
                    "@timestamp": {
                      "from": "now-5m"
                    }
                  }
                }
              }
            },
            "aggs": {
              "avg": {
                "avg": {
                  "field": "mos"
                }
              }
            }
          }
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.hits.total > 1"
      }
    },
    "transform": {},
    "actions": {
      "email_admin": {
        "throttle_period": "15m",
        "email": {
          "to": "mos@qxip.net",
          "subject": "Low MOS Detected: {{payload.aggregations.avg.value}} ",
          "priority": "high",
          "body": "Low MOS Detected:\n {{payload.aggregations.avg.value}} average with {{payload.aggregations.count.value}} measurements in 5 minutes"
        }
      }
    }
  }
}
```
the debug Log :
`{"type":"log","@timestamp":"2016-11-22T16:19:55Z","tags":["status","debug","KaaE"],"pid":1,"message":"Reloading Watchers..."}
{"type":"log","@timestamp":"2016-11-22T16:19:55Z","tags":["status","info","KaaE"],"pid":1,"message":"Executing watch: mos"}
{"type":"log","@timestamp":"2016-11-22T16:19:55Z","tags":["status","debug","KaaE","WATCHER DEBUG"],"pid":1,"message":"{ _index: 'watcher',\n  _type: 'watch',\n  _id: 'mos',\n  _score: 1,\n  _source: \n   { trigger: { schedule: [Object] },\n     input: { search: [Object] },\n     condition: { script: [Object] },\n     transform: {},\n     actions: { email_admin: [Object] } } }"}`

If i request the Cluster by curl:
 ```json

  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 86,
    "max_score": 1,
    "hits": [
      {
        "_index": "mos-2016.11.22",
        "_type": "mos",
        "_id": "AViMyCPhTDIkkYAWmKXZ",
        "_score": 1,
        "_source": {
          "mos": 5,
          "@timestamp": "2016-11-22T16:04:36.438"
        }
      },
[...some more hits]
    ]
  },
  "aggregations": {
    "avg": {
      "value": 3.197674418604651
    }
  }
}
```
I don't know what to do next to get things running.

Thank you for your assistance...

regards
Christian

**Comment by lmangani** [comment]
Could you change:
```
 "index": [
            "<mos-{now/d}>",
            "<mos-{now/d-1d}>"
          ],
```
with:
```
 "indices": [
            "<mos-{now/d}>",
            "<mos-{now/d-1d}>"
          ],
```

**Comment by cherweg** [comment]
I found an stacktrace in stderr of my Kibana Container:
```
Unhandled rejection Error: Bad Request
    at respond (/opt/kibana/node_modules/elasticsearch/src/lib/transport.js:238:15)
    at checkRespForFailure (/opt/kibana/node_modules/elasticsearch/src/lib/transport.js:201:7)
    at HttpConnector.<anonymous> (/opt/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
    at IncomingMessage.wrapper (/opt/kibana/node_modules/lodash/index.js:3095:19)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)
```
Could that be the reason?

regards
Christian

**Comment by lmangani** [comment]
Have you implemented the query change I suggested? I also updated the wiki.

**Comment by cherweg** [comment]
Thank you,
that did the trick!
 
Thank you very much..
regards
christian
