### ISSUE TITLE
When to use ctx.

### ISSUE THREAD

**Issue by cherweg** [sirensolutions/kaae#68]
in some of your [examples](https://github.com/sirensolutions/kaae/wiki/KAAE-Random-Examples) you use the keyword ctx : 
```json
  "condition": {
    "compare": {
      "ctx.payload.hits.total": {
        "gte": 1
      }
    }
  }
```
when to use ctx.payload... and when payload...?

regards
christian

**Comment by lmangani** [comment]
Hi @cherweg thanks for raising this issue, the example was outdated and has been replaced with the proper syntax
