### ISSUE TITLE
KAAE can't send the alart mail in HTML format

### ISSUE THREAD

**Issue by sitanxin** [sirensolutions/kaae#70]
1. Issue Description
KAAE could not send the mail in HTML Format.

**Comment by lmangani** [comment]
Hi @sitanxin 

HTML emails require the [email_html](https://github.com/sirensolutions/kaae/wiki/KAAE-Watcher-Actions#email-html) action instead of simply ```email``` - Check the wiki for examples.

**Comment by sitanxin** [comment]
Hi, in the wiki, it should the action as "email" instead of "email_html". Is it a mistype?
